if (CMAKE_C_COMPILER_ID MATCHES "GNU")
    set(CMAKE_C_FLAGS_INIT "-Wall -Wextra -Wno-unknown-pragmas -Wno-restrict -Wno-missing-field-initializers")
    set(CMAKE_C_FLAGS_DEBUG_INIT "-ggdb3")
    set(CMAKE_C_FLAGS_RELEASE_INIT "-O3 -DNDEBUG")
    set(CMAKE_C_FLAGS_RELWITHDEBINFO_INIT "-O2 -g -fno-omit-frame-pointer")
elseif(CMAKE_C_COMPILER_ID MATCHES "Clang")
    set(CMAKE_C_FLAGS_INIT "-Wall -Wextra -Wno-unknown-pragmas -Wno-missing-field-initializers")
    set(CMAKE_C_FLAGS_DEBUG_INIT "-ggdb3")
    set(CMAKE_C_FLAGS_RELEASE_INIT "-O3 -DNDEBUG")
    set(CMAKE_C_FLAGS_RELWITHDEBINFO_INIT "-O2 -g -fno-omit-frame-pointer")
else()
    message(FATAL_ERROR "Unsupported compiler: ${CMAKE_C_COMPILER_ID}")
endif()
