if (CMAKE_CXX_COMPILER_ID MATCHES "GNU")
    set(CMAKE_CXX_FLAGS_INIT "-Wall -Wextra -Wno-unknown-pragmas -Wno-restrict -Wno-missing-field-initializers")
    set(CMAKE_CXX_FLAGS_DEBUG_INIT "-ggdb3")
    set(CMAKE_CXX_FLAGS_RELEASE_INIT "-O3 -DNDEBUG")
    # set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "-O2 -ggdb -fno-omit-frame-pointer")
    set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "-O2 -ggdb -fno-omit-frame-pointer -fsanitize=address -fsanitize=null")
elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    set(CMAKE_CXX_FLAGS_INIT "-Wall -Wextra -Wno-unknown-pragmas -Wno-missing-field-initializers")
    set(CMAKE_CXX_FLAGS_DEBUG_INIT "-ggdb3")
    set(CMAKE_CXX_FLAGS_RELEASE_INIT "-O3 -DNDEBUG")
    set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "-O2 -ggdb -fno-omit-frame-pointer -fsanitize=address -fsanitize=null")
else()
    message(FATAL_ERROR "Unsupported compiler: ${CMAKE_CXX_COMPILER_ID}")
endif()
