name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:
    inputs:
      is_build_type:
        description: "put that to true if you want to use the custom build type"
        required: true
        type: boolean
        default: false
      BUILD_TYPE:
        description: "The build type (Release, Debug, RelWithDebInfo, etc.)"
        required: false
        type: string
        default: ""
      use_custom_compiler:
        description: "put that on true if you want tu use a custom compiler (by default it's GNU 9.4.0)"
        required: true
        type: boolean
        default: false
      CC_COMPILER:
        description: "the CC compiler path (eg. /usr/bin/clang-12)"
        required: false
        type: string
        default: ""
      CXX_COMPILER:
        description: "the CXX compiler path (eg. /usr/bin/clang++-12)"
        required: false
        type: string
        default: ""


env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CC: /usr/bin/clang-12
  CXX: /usr/bin/clang++-12

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup build type
      if: inputs.is_build_type
      env:
        BUILD_TYPE: ${{ inputs.BUILD_TYPE }}
      run: |
        echo "Setting build type to ${{ env.BUILD_TYPE }}\n"

    - name: Setup CC compiler
      if: inputs.use_custom_compiler
      env:
        CC: ${{ inputs.CC_COMPILER }}
      run: |
        echo "Setting CC compiler type to ${{ env.CC }}\n"

    - name: Setup CXX compiler
      if: inputs.use_custom_compiler
      env:
        CXX: ${{ inputs.CXX_COMPILER }}
      run: |
        echo "Setting CXX compiler type to ${{ env.CXX }}\n"


    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}

