# Name the workflow
name: CMake

on:
  # Trigger the workflow on push on the master branch
  push:
    branches: [ "master" ]
  # Trigger the workflow on pull request events
  pull_request:
    branches: [ "*" ]
  # Trigger the workflow manually
  workflow_dispatch:
    # Allow the user to enter custom parameters
    inputs:
      # Variable to specify if there is a custom build type
      is_build_type:
        description: "put that to true if you want to use the custom build type"
        required: true
        type: boolean
        default: false
      # Variable to specify the custom build type
      BUILD_TYPE:
        description: "The build type (Release, Debug, RelWithDebInfo, etc.)"
        required: false
        type: string
        default: ""
      # Variable to specify if there is a custom compiler to use instead of the default one
      use_custom_compiler:
        description: "put that on true if you want tu use a custom compiler (by default it's GNU 9.4.0)"
        required: true
        type: boolean
        default: false
      # Variable to specify the custom compiler for CC to use
      CC_COMPILER:
        description: "the CC compiler path (eg. /usr/bin/clang-12)"
        required: false
        type: string
        default: ""
      # Variable to specify the custom compiler for CXX to use
      CXX_COMPILER:
        description: "the CXX compiler path (eg. /usr/bin/clang++-12)"
        required: false
        type: string
        default: ""

# Define some environment variables for the workflow
env:
  # Customize the default CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  # Customize the default CC compiler here (GNU 9.4.0, clang 12, etc.)
  CC: /usr/bin/clang-14
  # Customize the default CXX compiler here (GNU 9.4.0, clang++ 12, etc.)
  CXX: /usr/bin/clang++-14

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: self-hosted

    steps:
    # Checkout the repository
    - uses: actions/checkout@v3

    # Test if there is a custom build type and if so set the coresponding environment variable to the custom build type
    - name: Setup build type
      if: inputs.is_build_type
      env:
        BUILD_TYPE: ${{ inputs.BUILD_TYPE }}
      run: |
        echo "Setting build type to ${{ env.BUILD_TYPE }}\n"

    # Test if there is a custom compiler to use and if so set the coresponding environment variable to the custom compiler
    - name: Setup CC and CXX compiler
      if: inputs.use_custom_compiler
      env:
        CC: ${{ inputs.CC_COMPILER }}
        CXX: ${{ inputs.CXX_COMPILER }}
      run: |
        echo "Setting CC compiler type to ${{ env.CC }}\n"
        echo "Setting CXX compiler type to ${{ env.CXX }}\n"

      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
    - name: Configure CMake
      run: |
        cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      # Build the program with the given configuration
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup build type
      if: inputs.is_build_type
      env:
        BUILD_TYPE: ${{ inputs.BUILD_TYPE }}
      run: |
        echo "Setting build type to ${{ env.BUILD_TYPE }}\n"

    - name: Setup CC and CXX compiler
      if: inputs.use_custom_compiler
      env:
        CC: ${{ inputs.CC_COMPILER }}
        CXX: ${{ inputs.CXX_COMPILER }}
      run: |
        echo "Setting CC compiler type to ${{ env.CC }}\n"
        echo "Setting CXX compiler type to ${{ env.CXX }}\n"

    - name: Configure CMake
      run: |
        cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D GTEST=true

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
